name: Get All Commits from Push

on:
  push:
    branches:
      - main
      - develop
      - feature/*   # Adjust if you have other branches to check

jobs:
  extract-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract all commit messages from push
      run: |
        # Path to the GitHub event JSON file
        event_file=$GITHUB_EVENT_PATH

        # Use jq to extract all commit messages
        commit_messages=$(jq -r '.commits[].message' "$event_file")

        pattern="^workitem [0-9]+ - .+

        echo "$commit_messages" | while IFS= read -r commit_message; do
          # Debug: Print the commit message being checked
          echo "Checking commit message: $commit_message"

          # Check if the message matches the pattern
          if ! [[ "$commit_message" =~ $pattern ]]; then
            echo "Error: Commit message '$commit_message' does not follow the required pattern 'workitem <num> - <subject>'"
            exit 1
          fi
        done
        echo "All commit messages follow the correct pattern."
